# ---- Randomly generated variables stored to AWS SecretsManager ----
# Generates the random api key
resource "random_id" "api_key" {
    byte_length = 32
}

resource "aws_secretsmanager_secret" "internal_api_key" {
  name = "gtfs/internal_api_key"
  description = "API Key generated by Terraform to authenticate incoming connections"
  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "internal_api_key" {
    secret_id = aws_secretsmanager_secret.internal_api_key.id
    secret_string = random_id.api_key.hex
}

# ---- Pre-known variables stored to AWS SecretsManager ----

resource "aws_secretsmanager_secret" "external_api_key" {
  name = "gtfs/external_api_key"
  description = "API Key used to authenticate with GTFS provider"
  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "external_api_key" {
    secret_id = aws_secretsmanager_secret.external_api_key.id
    secret_string = var.gtfs_provider_api_key
}

resource "aws_secretsmanager_secret" "external_api_url" {
  name = "gtfs/external_api_url"
  description = "URL used to poll GTFS provider"
  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "external_api_url" {
    secret_id = aws_secretsmanager_secret.external_api_url.id
    secret_string = var.gtfs_provider_api_url
}